### ISSUE TITLE
Comparing notes

### ISSUE THREAD

**Issue by betatim** [carolynvs/howtowhale#1]
More of a comment instead of issue:

Do people feel alright with handing you the API key? Last time I checked you only had one API key for all of carina which made me ask people to create a cluster and share the credentials file in `betatim/jupyterhub-carina` instead. I'd be interested to compare notes, this looks much more polished.

**Comment by carolynvs** [comment]
I have no clue if someone would trust me enough to do that. :smile: I am using SSL so that it couldn't be sniffed, and only use the key long enough to grab the zip file. Obviously a bad actor could wreak havoc with your api key, and a cluster zip does limit the damage. I just liked how much easier the flow is with the key, as you don't have to explain the whole zip dance. Ideally Carina would support oauth down the road, which is what I'm really root for.

In case it wasn't clear, I totally used your setup as a starting point. We used it for a PyLadies JupyterHub workshop and it was crazy useful. :+1:

**Comment by carolynvs** [comment]
I made a suggestion for oauth on the Carina feedback site and CC'd you in case you'd like to subscribe to the issue.

**Comment by betatim** [comment]
:+1: 

I don't have many data points on the zipfile approach either. It does take a lot of explaining though, which is a minus point.

Good to hear you found my setup useful! Something, something about copying being the best kind of flattery :)

**Comment by carolynvs** [comment]
So the point of my little project for here was:
1. To make a website (howtowhale.com) which is totes top secret stuff that will make me :moneybag:. jk
2. To play with your jupyterhub-carina and send back any fixes/improvements.

I'm still dorking around but once I get things figured out, would you be cool with PR's to move my tweaks back up to yours? I'm not looking to splinter what you've done. If we could support stuff like the zip uploads, api auth and eventually oauth in one repo, that would be darn useful.

**Comment by betatim** [comment]
1. join forces
2. ...
3. :moneybag: :moneybag: :moneybag: 

Sounds like a plan to me! Eventually I want to add something like this to `everware/everware`. Then you can specify a git repo to clone _and_ bring your own compute. That is my plan for rolling in :money_with_wings: ;)

**Comment by carolynvs** [comment]
:+1:

**Comment by carolynvs** [comment]
FYI, I am working on implementing oauth for Carina. Once that's finished and deployed, we can register an oauth applications and just use standard oauth2 to login. The following scopes will be available:
- `identity`: Basic login only.
- `create_cluster`: Create clusters on the user's behalf.
- `cluster_credentials`: Retrieve the credentials zip file for a user's cluster.

Once logged in, an oauth app can hit the following endpoints
- `GET /clusters/<cluster-name>`: Retrieves the cluster credentials.
- `PUT /clsuters/<cluster-name>`: Create the named cluster. Returns immediately, app must poll for the credentials until the zip is returned instead of 404.

As part of this, I'm writing an CarinaAuthenticator/CarinaSpawner, which does the Carina oauth dance and uses the /clusters endpoint. That will be submitted upstream to jupyter/oauthenticator.

**Comment by betatim** [comment]
Sounds good. Let me know if I can help somehow. There are no spawners in `jupyter/oauthenticator` at the moment, so will the spawner go to `jupyter/dockerspawner`? I think that would be a good home for it.

I've subscribed to getcarina/carina-oauth#2

**Comment by carolynvs** [comment]
Doh! Yes, I'm hoping to land both classes in the appropriate upstream repos: oauthenticator and dockerspawner.

**Comment by betatim** [comment]
:thumbsup:

**Comment by carolynvs** [comment]
FYI, the oauth endpoint is now official! https://getcarina.com/docs/reference/oauth-integration/
Now onto getting all these goodies back in Jupyter!
